services:
  backend:
    build: 
      context: ./backend
      dockerfile: dockerfile
    restart: always
    env_file:
      - ./backend/.env
    ports: 
      - "${PORT}:21165"
    depends_on:
      - mongo    
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mongodb://admin:mypass@mongo:27017/api_erp?authSource=admin
    labels:
      - traefik.enable=true
      - traefik.http.routers.${SQUAD_NAME}-backend-http.rule=Host(`api-${SQUAD_NAME}.qacoders.dev.br`)
      - traefik.http.routers.${SQUAD_NAME}-backend-http.entrypoints=web
      - traefik.http.routers.${SQUAD_NAME}-backend-https.tls=true
      - traefik.http.routers.${SQUAD_NAME}-backend-https.tls.certresolver=letsencrypt
      - traefik.http.routers.${SQUAD_NAME}-backend-https.entrypoints=websecure
      - traefik.http.routers.${SQUAD_NAME}-backend-https.rule=Host(`api-${SQUAD_NAME}.qacoders.dev.br`)
    networks:
      - traefik
    mem_limit: 1g
    cpus: "0.5"    

  frontend:
    build: 
      context: ./frontend
      dockerfile: dockerfile
    restart: always
    env_file:
      - ./frontend/.env
    ports:
      - "1${PORT}:3000"
    depends_on:
      - backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.${SQUAD_NAME}-frontend-http.rule=Host(`${SQUAD_NAME}.qacoders.dev.br`)
      - traefik.http.routers.${SQUAD_NAME}-frontend-http.entrypoints=web
      - traefik.http.routers.${SQUAD_NAME}-frontend-https.tls=true
      - traefik.http.routers.${SQUAD_NAME}-frontend-https.tls.certresolver=letsencrypt
      - traefik.http.routers.${SQUAD_NAME}-frontend-https.entrypoints=websecure
      - traefik.http.routers.${SQUAD_NAME}-frontend-https.rule=Host(`${SQUAD_NAME}.qacoders.dev.br`)

    networks:
      - traefik
    mem_limit: 128m
    cpus: "0.1"

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "2${PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=mypass 
    volumes:
      - mongo_data:/data/db
    networks:
      - traefik
    mem_limit: 128m
    cpus: "0.1"

volumes:
  mongo_data:

networks:
  traefik:
    external: true
